{% set name = "mne-videobrowser" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mne_videobrowser-{{ version }}.tar.gz
  sha256: 8fb8c0492c5b6b3a74216a8af0a9127a8fe87002bcb1a9fcbdb07eba9747e227

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mne-base >=1.10
    - mne-qt-browser >=0.7
    - pyside
    - opencv >=4.8 *headless*  # avoid GUI dependencies (Qt) here
    - python-sounddevice >=0.5

test:
  imports:
    - mne_videobrowser
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Python package for browsing video and audio time-synchronized to MEG/EEG data
  home: https://github.com/ttaiv/mne-videobrowser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://mne-videobrowser.readthedocs.io
  dev_url: https://github.com/ttaiv/mne-videobrowser

extra:
  recipe-maintainers:
    - ttaiv
    - larsoner
